# Generated by Django 5.2 on 2025-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimPdv',
            fields=[
                ('pdv_sk', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_pdv', models.CharField(max_length=100, unique=True, verbose_name='Código PDV')),
                ('nombre_pdv', models.CharField(max_length=255, verbose_name='Nombre PDV')),
                ('tipo_pdv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de PDV')),
                ('formato_pdv', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato PDV')),
                ('direccion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento_geo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento Geográfico')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha Apertura')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha Cierre')),
                ('estado_pdv', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('remodelacion', 'En Remodelación')], default='activo', max_length=20, verbose_name='Estado del PDV')),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metros Cuadrados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Punto de Venta (PDV)',
                'verbose_name_plural': 'Puntos de Venta (PDV)',
                'db_table': 'dim_pdv',
                'ordering': ['nombre_pdv'],
            },
        ),
    ]
