# Generated by Django 5.2 on 2025-05-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimpdv',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Altura (mts)'),
        ),
        migrations.AddField(
            model_name='dimpdv',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ancho (mts)'),
        ),
        migrations.AddField(
            model_name='dimpdv',
            name='esquinero',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (0, 'No'), (1, 'Sí')], null=True, verbose_name='¿Es Esquinero?'),
        ),
        migrations.AddField(
            model_name='dimpdv',
            name='largo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Largo (mts)'),
        ),
        migrations.AddField(
            model_name='dimpdv',
            name='mt_lineal_exhibicion',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (0, 'No'), (1, 'Sí')], null=True, verbose_name='¿Tiene Mueble Lineal de Exhibición?'),
        ),
        migrations.AddField(
            model_name='dimpdv',
            name='tamano_puerta',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (0, 'No'), (1, 'Sí')], null=True, verbose_name='¿Tamaño de Puerta Especial?'),
        ),
        migrations.AddField(
            model_name='dimpdv',
            name='vitrina_exhibicion',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (0, 'No'), (1, 'Sí')], null=True, verbose_name='¿Tiene Vitrina de Exhibición?'),
        ),
        migrations.AlterField(
            model_name='dimpdv',
            name='formato_pdv',
            field=models.CharField(blank=True, choices=[('tradicional', 'Tradicional'), ('minimarket', 'Minimarket'), ('e_commerce', 'E-commerce')], max_length=20, null=True, verbose_name='Formato PDV'),
        ),
        migrations.AlterField(
            model_name='dimpdv',
            name='metros_cuadrados',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Metros Cuadrados (calculado)'),
        ),
        migrations.AlterField(
            model_name='dimpdv',
            name='tipo_pdv',
            field=models.CharField(blank=True, choices=[('barrio', 'Barrio'), ('c_comercial', 'Centro Comercial'), ('tienda_oculta', 'Tienda Oculta (Bodega/Ecommerce)')], max_length=20, null=True, verbose_name='Tipo de PDV'),
        ),
    ]
