# Generated by Django 5.2 on 2025-05-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dimpdv_altura_dimpdv_ancho_dimpdv_esquinero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimpdv',
            name='mt_lineal_exhibicion',
        ),
        migrations.AddField(
            model_name='dimpdv',
            name='metros_lineales_exhibicion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Metros Lineales de Exhibición'),
        ),
        migrations.AlterField(
            model_name='dimpdv',
            name='tamano_puerta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tamaño de Puerta (mts)'),
        ),
    ]
