# Generated by Django 5.2 on 2025-05-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_dimpdv_mt_lineal_exhibicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCampanaEcommerce',
            fields=[
                ('campana_ecommerce_sk', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campana', models.CharField(max_length=150, verbose_name='Nombre Campaña E-commerce')),
                ('descripcion_campana', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaña de E-commerce',
                'verbose_name_plural': 'Campañas de E-commerce',
                'db_table': 'dim_campana_ecommerce',
                'ordering': ['-fecha_inicio', 'nombre_campana'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='chk_fecha_fin_ecom_gte_inicio')],
            },
        ),
        migrations.CreateModel(
            name='DimCampanaMerchandising',
            fields=[
                ('campana_merchandising_sk', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campana', models.CharField(max_length=150, verbose_name='Nombre Campaña Merchandising')),
                ('descripcion_campana', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaña de Merchandising',
                'verbose_name_plural': 'Campañas de Merchandising',
                'db_table': 'dim_campana_merchandising',
                'ordering': ['-fecha_inicio', 'nombre_campana'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='chk_fecha_fin_merch_gte_inicio')],
            },
        ),
    ]
