# Generated by Django 5.2 on 2025-05-28 13:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dimcampanaecommerce_dimcampanamerchandising'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimFecha',
            fields=[
                ('fecha_sk', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Fecha')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('dia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.PositiveSmallIntegerField()),
                ('trimestre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('semestre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('dia_semana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('nombre_dia', models.CharField(max_length=10)),
                ('nombre_mes', models.CharField(max_length=10)),
                ('es_fin_semana', models.BooleanField(default=False)),
                ('es_feriado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dimensión Fecha',
                'verbose_name_plural': 'Dimensiones de Fechas',
                'db_table': 'dim_fecha',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fecha'], name='dim_fecha_fecha_bec317_idx'), models.Index(fields=['anio', 'mes'], name='dim_fecha_anio_40d763_idx'), models.Index(fields=['es_fin_semana'], name='dim_fecha_es_fin__cc7e7a_idx'), models.Index(fields=['es_feriado'], name='dim_fecha_es_feri_630914_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimProducto',
            fields=[
                ('producto_sk', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Producto')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subcategoría')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('unidades_por_caja', models.PositiveIntegerField(default=1, verbose_name='Unidades por Caja')),
                ('unidades_por_blister', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidades por Blister')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'dim_producto',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='dim_product_codigo_4b9536_idx'), models.Index(fields=['nombre'], name='dim_product_nombre_c00b29_idx'), models.Index(fields=['categoria'], name='dim_product_categor_e06fad_idx'), models.Index(fields=['marca'], name='dim_product_marca_a86661_idx'), models.Index(fields=['activo'], name='dim_product_activo_f29dfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactInventarios',
            fields=[
                ('inventario_sk', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Inventario')),
                ('fecha', models.DateField(verbose_name='Fecha del Inventario')),
                ('cantidad_existencias', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad en Existencia')),
                ('valor_existencias', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor en Existencia')),
                ('costo_promedio', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Costo Promedio')),
                ('rotacion_dias', models.IntegerField(blank=True, null=True, verbose_name='Rotación en Días')),
                ('rotacion_semanas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rotación en Semanas')),
                ('dias_stock', models.IntegerField(blank=True, null=True, verbose_name='Días de Stock')),
                ('nivel_stock', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nivel de Stock')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('pdv', models.ForeignKey(db_column='pdv_id', on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimpdv', verbose_name='Punto de Venta')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'fact_inventarios',
                'ordering': ['-fecha', 'pdv__nombre_pdv'],
                'indexes': [models.Index(fields=['fecha'], name='fact_invent_fecha_12e39b_idx'), models.Index(fields=['pdv'], name='fact_invent_pdv_id_a7a9d3_idx'), models.Index(fields=['nivel_stock'], name='fact_invent_nivel_s_6a43dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('pdv', 'fecha'), name='unique_inventario_pdv_fecha')],
            },
        ),
        migrations.CreateModel(
            name='FactRotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Producto')),
                ('codigo_pdv', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código PDV')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('venta_unidades', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Venta Unidades')),
                ('venta_cajas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Venta Cajas')),
                ('venta_blisters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Venta Blisters')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Costo Unitario')),
                ('precio_venta_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio Venta Unitario')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costo Total')),
                ('venta_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Venta Total')),
                ('margen_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Margen Bruto')),
                ('margen_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Margen %')),
                ('inventario_unidades_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Inventario Inicial (Unidades)')),
                ('inventario_unidades_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Inventario Final (Unidades)')),
                ('dias_inventario', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Días de Inventario')),
                ('rotacion_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Rotación del Mes')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_dim', models.ForeignKey(blank=True, db_column='fecha_sk', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimfecha', verbose_name='Fecha')),
                ('pdv', models.ForeignKey(blank=True, db_column='pdv_sk', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimpdv', verbose_name='Punto de Venta')),
                ('producto', models.ForeignKey(blank=True, db_column='producto_sk', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimproducto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Rotación de Inventario',
                'verbose_name_plural': 'Rotaciones de Inventario',
                'db_table': 'fact_rotacion',
                'ordering': ['-fecha', 'codigo_pdv', 'codigo_producto'],
                'indexes': [models.Index(fields=['codigo_producto', 'codigo_pdv', 'fecha'], name='fact_rotaci_codigo__bb9fe3_idx'), models.Index(fields=['fecha'], name='fact_rotaci_fecha_b5bf30_idx'), models.Index(fields=['codigo_pdv'], name='fact_rotaci_codigo__76b350_idx'), models.Index(fields=['codigo_producto'], name='fact_rotaci_codigo__e29de0_idx')],
            },
        ),
    ]
